In [71]:
import torch
import torch.nn as nn
import nltk
import torch.optim as optim
import numpy as np
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
from collections import Counter

In [72]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [73]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading punkt_tab: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


False

In [74]:
tokens = word_tokenize(document)

In [75]:
tokens

['About',
 'the',
 'Program',
 'What',
 'is',
 'the',
 'course',
 'fee',
 'for',
 'Data',
 'Science',
 'Mentorship',
 'Program',
 '(',
 'DSMP',
 '2023',
 ')',
 'The',
 'course',
 'follows',
 'a',
 'monthly',
 'subscription',
 'model',
 'where',
 'you',
 'have',
 'to',
 'make',
 'monthly',
 'payments',
 'of',
 'Rs',
 '799/month',
 '.',
 'What',
 'is',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 '?',
 'The',
 'total',
 'duration',
 'of',
 'the',
 'course',
 'is',
 '7',
 'months',
 '.',
 'So',
 'the',
 'total',
 'course',
 'fee',
 'becomes',
 '799',
 '*',
 '7',
 '=',
 'Rs',
 '5600',
 '(',
 'approx',
 '.',
 ')',
 'What',
 'is',
 'the',
 'syllabus',
 'of',
 'the',
 'mentorship',
 'program',
 '?',
 'We',
 'will',
 'be',
 'covering',
 'the',
 'following',
 'modules',
 ':',
 'Python',
 'Fundamentals',
 'Python',
 'libraries',
 'for',
 'Data',
 'Science',
 'Data',
 'Analysis',
 'SQL',
 'for',
 'Data',
 'Science',
 'Maths',
 'for',
 'Machine',
 'Learning',
 'ML',
 'Algorithms',
 'P

In [76]:
from collections import Counter

counter = Counter(tokens)

vocab = {
    '<PAD>': 0,
    '<UNK>': 1
}

min_freq = 1

for word, freq in counter.items():

    if freq >= min_freq:
        vocab[word] = len(vocab)

In [77]:
vocab

{'<PAD>': 0,
 '<UNK>': 1,
 'About': 2,
 'the': 3,
 'Program': 4,
 'What': 5,
 'is': 6,
 'course': 7,
 'fee': 8,
 'for': 9,
 'Data': 10,
 'Science': 11,
 'Mentorship': 12,
 '(': 13,
 'DSMP': 14,
 '2023': 15,
 ')': 16,
 'The': 17,
 'follows': 18,
 'a': 19,
 'monthly': 20,
 'subscription': 21,
 'model': 22,
 'where': 23,
 'you': 24,
 'have': 25,
 'to': 26,
 'make': 27,
 'payments': 28,
 'of': 29,
 'Rs': 30,
 '799/month': 31,
 '.': 32,
 'total': 33,
 'duration': 34,
 '?': 35,
 '7': 36,
 'months': 37,
 'So': 38,
 'becomes': 39,
 '799': 40,
 '*': 41,
 '=': 42,
 '5600': 43,
 'approx': 44,
 'syllabus': 45,
 'mentorship': 46,
 'program': 47,
 'We': 48,
 'will': 49,
 'be': 50,
 'covering': 51,
 'following': 52,
 'modules': 53,
 ':': 54,
 'Python': 55,
 'Fundamentals': 56,
 'libraries': 57,
 'Analysis': 58,
 'SQL': 59,
 'Maths': 60,
 'Machine': 61,
 'Learning': 62,
 'ML': 63,
 'Algorithms': 64,
 'Practical': 65,
 'MLOPs': 66,
 'Case': 67,
 'studies': 68,
 'You': 69,
 'can': 70,
 'check': 71,
 'de

In [78]:
len(vocab)

312

In [79]:
input_sentences = document.split('\n')

In [80]:
def text_to_indices(sentence, vocab):
    numerical_sentence = []

    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
            numerical_sentence.append(vocab['<UNK>'])    
    return numerical_sentence        

In [81]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))


In [82]:
input_numerical_sentences

[[133, 3, 47],
 [224, 6, 3, 7, 8, 9, 1, 1, 46, 47, 13, 1, 15, 16],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 20, 28, 29, 1, 31, 32],
 [224, 6, 3, 33, 34, 29, 3, 7, 35],
 [3,
  33,
  34,
  29,
  3,
  7,
  6,
  36,
  37,
  32,
  103,
  3,
  33,
  7,
  8,
  39,
  40,
  41,
  36,
  42,
  1,
  43,
  13,
  44,
  32,
  16],
 [224, 6, 3, 45, 29, 3, 46, 47, 35],
 [175, 49, 50, 51, 3, 52, 53, 54],
 [1, 1],
 [1, 57, 9, 1, 1],
 [1, 1],
 [1, 9, 1, 1],
 [1, 9, 1, 1],
 [1, 1],
 [1, 1],
 [1],
 [176, 68],
 [24, 70, 71, 3, 72, 45, 73, 74, 75, 54, 1],
 [49, 1, 1, 79, 1, 50, 19, 81, 29, 82, 47, 35],
 [199, 84, 1, 79, 1, 1, 85, 86, 87, 19, 81, 29, 82, 47, 88, 89, 90, 32],
 [224, 91, 1, 93, 19, 94, 95, 35, 49, 1, 96, 19, 97, 29, 3, 95, 35],
 [1,
  99,
  100,
  101,
  86,
  102,
  84,
  103,
  104,
  91,
  24,
  93,
  19,
  95,
  24,
  70,
  105,
  106,
  79,
  107,
  3,
  97,
  32],
 [23, 70, 1, 109, 3, 110, 111, 35],
 [1,
  82,
  113,
  114,
  26,
  115,
  116,
  117,
  116,
  118,
  119,
  29,
  3,


In [83]:
training_sequence = []
for sentence in input_numerical_sentences:

  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [84]:
training_sequence

[[133, 3],
 [133, 3, 47],
 [224, 6],
 [224, 6, 3],
 [224, 6, 3, 7],
 [224, 6, 3, 7, 8],
 [224, 6, 3, 7, 8, 9],
 [224, 6, 3, 7, 8, 9, 1],
 [224, 6, 3, 7, 8, 9, 1, 1],
 [224, 6, 3, 7, 8, 9, 1, 1, 46],
 [224, 6, 3, 7, 8, 9, 1, 1, 46, 47],
 [224, 6, 3, 7, 8, 9, 1, 1, 46, 47, 13],
 [224, 6, 3, 7, 8, 9, 1, 1, 46, 47, 13, 1],
 [224, 6, 3, 7, 8, 9, 1, 1, 46, 47, 13, 1, 15],
 [224, 6, 3, 7, 8, 9, 1, 1, 46, 47, 13, 1, 15, 16],
 [3, 7],
 [3, 7, 18],
 [3, 7, 18, 19],
 [3, 7, 18, 19, 20],
 [3, 7, 18, 19, 20, 21],
 [3, 7, 18, 19, 20, 21, 22],
 [3, 7, 18, 19, 20, 21, 22, 23],
 [3, 7, 18, 19, 20, 21, 22, 23, 24],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 20],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 20, 28],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 20, 28, 29],
 [3, 7, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 20, 28, 29, 1],
 [3, 7, 18, 19, 20, 21, 2

In [85]:
len_list = []

for sentence in training_sequence:
    len_list.append(len(sentence))

max(len_list)

62

In [86]:
padded_training_sequence = []
for sequence in training_sequence:

  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [87]:
len(padded_training_sequence[0])

62

In [88]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [89]:
x = padded_training_sequence[:,:-1]
y = padded_training_sequence[:, -1]

In [90]:
class CustomDataset(Dataset):

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return self.x.shape[0]    
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]

In [91]:
dataset = CustomDataset(x,y)

In [92]:
dataloader = DataLoader(dataset, shuffle=True, pin_memory=True)

In [93]:
for input, output in dataloader:
    print(input, output)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]) tensor([191])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  82,   6,  26, 286,
         282, 300, 283, 287,  87]]) tensor([288])
tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  82, 235,   6, 236,  84, 103, 237, 238,  32,  24,  70, 107,
           3, 233, 239, 163,  21,   6, 240,  32,   1,  24,  25, 241,  21, 191,
         242,   1,  84,  24,  49]]) tensor([50])
tensor([[  0,   0,   0,   0,   0,   0,   0,

In [ ]:
#In Pytorch we have to set bidirectional=True Inside rnn, lstm or gru to make it bidirectional

In [ ]:
# class BiGRU(nn.Module):

#     def __init__(self, vocab_size):

#         super().__init__()

#         self.embedding = nn.Embedding(vocab_size, 100)

#         self.gru = nn.GRU(
#             input_size=100,
#             hidden_size=150,
#             batch_first=True,
#             bidirectional=True
#         )

#         self.fc = nn.Linear(300, vocab_size)

#     def forward(self, x):

#         embedded = self.embedding(x)

#         intermediate_hidden_states, final_hidden_state = self.gru(embedded)

#         # final_hidden_state shape:
#         # (num_layers * num_directions, batch_size, hidden_size)

#         # forward hidden state
#         forward_hidden = final_hidden_state[0]

#         # backward hidden state
#         backward_hidden = final_hidden_state[1]

#         # concatenate
#         combined_hidden = torch.cat(
#             (forward_hidden, backward_hidden),
#             dim=1
#         )

#         output = self.fc(combined_hidden)

#         return output

In [94]:
class GRU(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.gru = nn.GRU(100, 150, batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states, final_hidden_state = self.gru(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [95]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

model = GRU(len(vocab)).to(device)

In [96]:
epochs = 50
lr = 0.01

loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr)

In [97]:
for epoch in range(epochs):
    total_loss = 0
    for batch_features, batch_lables in dataloader:
        batch_features, batch_lables = batch_features.to(device), batch_lables.to(device)

        y_pred = model(batch_features)

        loss = loss_function(y_pred, batch_lables)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print(total_loss/len(dataloader))    

6.619128805710606
7.013860381500415
7.020434626282705
6.127278308307853
5.103479240043234
5.56808515669527
5.176768690828574
5.2188371800869415
5.065500114736338
5.187341089015058
5.062610360593961
5.97601233008014
4.1907848190187575
3.506219188182929
3.9159624847030585
3.8603430260503275
4.463735715128813
5.191660623707755
4.692833670741184
4.0039208275385265
3.9243935511619226
4.303510200941773
4.359805822739827
4.287119910864203
3.959182309357339
3.637751120040599
3.326592660802799
3.574544951608806
4.090510626960322
4.19005519339477
4.606533284676026
3.342615589759318
3.5477390690427777
3.0485404299595946
2.8883917071344385
3.41068613753933
3.305957411917731
4.354698955963965
3.8762781777948003
4.164554149129801
3.7750131017078106
3.501342712603057
3.324834713822684
4.089813887654686
4.388560036468239
3.5419282043756204
3.2729366449905415
3.5960857623097753
3.844569647882286
3.7122216676466038


In [98]:
# prediction

def prediction(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_text = torch.tensor(
    [0] * (61 - len(numerical_text)) + numerical_text,
    dtype=torch.long
).unsqueeze(0).to(device)

  # send to model
  output = model(padded_text)

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return text + " " + list(vocab.keys())[index]

In [99]:
prediction(model, vocab, "The course follows a monthly")

'The course follows a monthly subscription'

In [100]:
import time

num_tokens = 10
input_text = "hi how are"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


hi how are recorded
hi how are recorded a
hi how are recorded a to
hi how are recorded a to in
hi how are recorded a to in the
hi how are recorded a to in the sessions
hi how are recorded a to in the sessions ?
hi how are recorded a to in the sessions ? ?
hi how are recorded a to in the sessions ? ? <UNK>
hi how are recorded a to in the sessions ? ? <UNK> or
