In [1]:
import torch

In [3]:
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.rand(2,4)

tensor([[0.8061, 0.4595, 0.7853, 0.9243],
        [0.9638, 0.3866, 0.5423, 0.4431]])

In [8]:
torch.rand(2,4)

tensor([[0.3066, 0.6718, 0.8749, 0.9989],
        [0.4960, 0.8533, 0.8941, 0.4390]])

In [9]:
torch.manual_seed(100)
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [10]:
torch.manual_seed(100)
torch.rand(2,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [11]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [13]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [14]:
torch.eye(2,3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [15]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [16]:
# Tensor Shapes

x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
torch.rand_like(x, dtype=torch.float)

tensor([0.2080, 0.1180, 0.1217])

In [22]:
# Tensor Data Types
x.dtype

torch.int64

In [26]:
x = torch.tensor([1,2,3], dtype=torch.float)
x

tensor([1., 2., 3.])

In [27]:
x.to(int)

tensor([1, 2, 3])

In [3]:
# Scalar Multiplication
import torch
x = torch.rand(2,2)
x

tensor([[0.7601, 0.9925],
        [0.7322, 0.0537]])

In [4]:
x + 1

tensor([[1.7601, 1.9925],
        [1.7322, 1.0537]])

In [5]:
x - 1

tensor([[-0.2399, -0.0075],
        [-0.2678, -0.9463]])

In [6]:
x * 2

tensor([[1.5201, 1.9849],
        [1.4644, 0.1074]])

In [7]:
x / 1

tensor([[0.7601, 0.9925],
        [0.7322, 0.0537]])

In [8]:
x // 1

tensor([[0., 0.],
        [0., 0.]])

In [9]:
x % 1

tensor([[0.7601, 0.9925],
        [0.7322, 0.0537]])

In [10]:
x ** 2

tensor([[0.5777, 0.9850],
        [0.5361, 0.0029]])

In [11]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.8315, 0.4424, 0.8235],
        [0.2561, 0.2227, 0.1846]])
tensor([[0.6684, 0.5848, 0.7383],
        [0.8583, 0.4634, 0.7595]])


In [12]:
a + b

tensor([[1.4999, 1.0272, 1.5618],
        [1.1144, 0.6861, 0.9441]])

In [13]:
a - b

tensor([[ 0.1631, -0.1424,  0.0851],
        [-0.6022, -0.2407, -0.5749]])

In [14]:
a * b

tensor([[0.5558, 0.2587, 0.6080],
        [0.2198, 0.1032, 0.1402]])

In [15]:
a / b

tensor([[1.2441, 0.7565, 1.1153],
        [0.2983, 0.4806, 0.2430]])

In [16]:
a // b

tensor([[1., 0., 1.],
        [0., 0., 0.]])

In [17]:
a ** b

tensor([[0.8840, 0.6207, 0.8664],
        [0.3106, 0.4986, 0.2771]])

In [18]:
a % b

tensor([[0.1631, 0.4424, 0.0851],
        [0.2561, 0.2227, 0.1846]])

In [19]:
c = torch.tensor([1,2,3,4])
c

tensor([1, 2, 3, 4])

In [20]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [21]:
torch.negative(c)

tensor([-1, -2, -3, -4])

In [23]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [24]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [25]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [26]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [27]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [28]:
# Reduction Operation

x = torch.randint(size=(2,3), dtype=torch.float, low=0, high=10)
x

tensor([[1., 5., 8.],
        [6., 8., 3.]])

In [30]:
torch.sum(x)

tensor(31.)

In [31]:
torch.sum(x, dim=0)

tensor([ 7., 13., 11.])

In [32]:
torch.sum(x, dim=1)

tensor([14., 17.])

In [33]:
torch.mean(x)

tensor(5.1667)

In [34]:
torch.mean(x, dim=0)

tensor([3.5000, 6.5000, 5.5000])

In [35]:
torch.median(x)

tensor(5.)

In [36]:
torch.prod(x)

tensor(5760.)

In [37]:
torch.max(x)

tensor(8.)

In [38]:
torch.min(x)

tensor(1.)

In [39]:
torch.var(x)

tensor(7.7667)

In [40]:
torch.argmax(x)

tensor(2)

In [41]:
torch.argmin(x)

tensor(0)

In [42]:
torch.std(x)

tensor(2.7869)

In [46]:
# Matrix Operation

a = torch.randint(size=(2,3), low=0, high=10)
b = torch.randint(size=(3,2), low=0, high=10)

print(a)
print(b)

tensor([[7, 1, 2],
        [0, 2, 1]])
tensor([[6, 6],
        [1, 6],
        [9, 7]])


In [53]:
torch.transpose(b, 0, 1)

tensor([[6, 1, 9],
        [6, 6, 7]])

In [47]:
torch.matmul(a, b)

tensor([[61, 62],
        [11, 19]])

In [48]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector1)

tensor(5)

In [50]:
square_matix = torch.rand(size=(3,3))
square_matix

tensor([[0.6431, 0.0121, 0.7622],
        [0.6453, 0.4213, 0.5684],
        [0.2218, 0.4417, 0.6647]])

In [51]:
torch.inverse(square_matix)

tensor([[ 0.1797,  2.0411, -1.9515],
        [-1.8810,  1.6049,  0.7844],
        [ 1.1902, -1.7476,  1.6342]])

In [52]:
torch.det(square_matix)

tensor(0.1610)

In [55]:
# Comparision
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 3, 2],
        [9, 1, 1]])
tensor([[5, 4, 4],
        [5, 0, 1]])


In [56]:
i > j

tensor([[False, False, False],
        [ True,  True, False]])

In [57]:
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [58]:
i == j

tensor([[ True, False, False],
        [False, False,  True]])

In [59]:
i != j

tensor([[False,  True,  True],
        [ True,  True, False]])

In [60]:
i >= j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [61]:
i <= j

tensor([[ True,  True,  True],
        [False, False,  True]])

In [62]:
# Special functions

x = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
x

tensor([[3., 3., 8.],
        [5., 3., 6.]])

In [63]:
torch.log(x)

tensor([[1.0986, 1.0986, 2.0794],
        [1.6094, 1.0986, 1.7918]])

In [64]:
torch.exp(x)

tensor([[  20.0855,   20.0855, 2980.9580],
        [ 148.4132,   20.0855,  403.4288]])

In [65]:
torch.sqrt(x)

tensor([[1.7321, 1.7321, 2.8284],
        [2.2361, 1.7321, 2.4495]])

In [66]:
torch.sigmoid(x)

tensor([[0.9526, 0.9526, 0.9997],
        [0.9933, 0.9526, 0.9975]])

In [67]:
torch.relu(x)

tensor([[3., 3., 8.],
        [5., 3., 6.]])

In [68]:
torch.softmax(x, dim=0)

tensor([[0.1192, 0.5000, 0.8808],
        [0.8808, 0.5000, 0.1192]])

In [69]:
# Inplace Operations

m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2545, 0.3612, 0.0046],
        [0.7076, 0.3706, 0.1618]])
tensor([[0.6375, 0.7834, 0.1481],
        [0.7103, 0.9680, 0.7026]])


In [70]:
m + n

tensor([[0.8920, 1.1446, 0.1527],
        [1.4179, 1.3386, 0.8644]])

In [71]:
m.add_(n)

tensor([[0.8920, 1.1446, 0.1527],
        [1.4179, 1.3386, 0.8644]])

In [72]:
m

tensor([[0.8920, 1.1446, 0.1527],
        [1.4179, 1.3386, 0.8644]])

In [73]:
torch.relu(m)

tensor([[0.8920, 1.1446, 0.1527],
        [1.4179, 1.3386, 0.8644]])

In [74]:
m.relu_()

tensor([[0.8920, 1.1446, 0.1527],
        [1.4179, 1.3386, 0.8644]])

In [75]:
m

tensor([[0.8920, 1.1446, 0.1527],
        [1.4179, 1.3386, 0.8644]])

In [76]:
# Copying Tensor

m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9303, 0.5476, 0.4153],
        [0.3004, 0.3397, 0.1803]])
tensor([[0.9638, 0.0634, 0.6855],
        [0.9585, 0.4371, 0.2861]])


In [77]:
m = n

In [78]:
m

tensor([[0.9638, 0.0634, 0.6855],
        [0.9585, 0.4371, 0.2861]])

In [79]:
n

tensor([[0.9638, 0.0634, 0.6855],
        [0.9585, 0.4371, 0.2861]])

In [83]:
n[0][0] = 0

In [84]:
m

tensor([[0.0000, 0.0634, 0.6855],
        [0.9585, 0.4371, 0.2861]])

In [85]:
n

tensor([[0.0000, 0.0634, 0.6855],
        [0.9585, 0.4371, 0.2861]])

In [86]:
m = n.clone()

In [87]:
n[0][0]=10

In [88]:
m

tensor([[0.0000, 0.0634, 0.6855],
        [0.9585, 0.4371, 0.2861]])

In [89]:
n

tensor([[10.0000,  0.0634,  0.6855],
        [ 0.9585,  0.4371,  0.2861]])

In [90]:
# Tensor Operation on GPU

torch.cuda.is_available()

True

In [91]:
device = torch.device('cuda')

In [92]:
torch.rand(size=(2,3), device=device)

tensor([[0.1006, 0.8646, 0.2235],
        [0.0290, 0.3890, 0.4336]], device='cuda:0')

In [93]:
a = torch.rand(size=(2,3))
a

tensor([[0.4547, 0.5465, 0.4741],
        [0.5166, 0.7260, 0.6727]])

In [95]:
b = a.to(device)
b

tensor([[0.4547, 0.5465, 0.4741],
        [0.5166, 0.7260, 0.6727]], device='cuda:0')

In [97]:
b + 2

tensor([[2.4547, 2.5465, 2.4741],
        [2.5166, 2.7260, 2.6727]], device='cuda:0')

In [98]:
# Reshaping Tensors

x = torch.ones(4,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
x.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [100]:
x.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
b = torch.rand(2,3,4)
b

tensor([[[0.1412, 0.8377, 0.6101, 0.2060],
         [0.4012, 0.9401, 0.2163, 0.8781],
         [0.8097, 0.1554, 0.8213, 0.8296]],

        [[0.8699, 0.2046, 0.2697, 0.5071],
         [0.7456, 0.5035, 0.7376, 0.6594],
         [0.5870, 0.3508, 0.0737, 0.4395]]])

In [104]:
b.permute(2,1,0)

tensor([[[0.1412, 0.8699],
         [0.4012, 0.7456],
         [0.8097, 0.5870]],

        [[0.8377, 0.2046],
         [0.9401, 0.5035],
         [0.1554, 0.3508]],

        [[0.6101, 0.2697],
         [0.2163, 0.7376],
         [0.8213, 0.0737]],

        [[0.2060, 0.5071],
         [0.8781, 0.6594],
         [0.8296, 0.4395]]])

In [107]:
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [108]:
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

In [109]:
# Numpy and Pandas 

import numpy as np

array = np.array([1,2,3])
array

array([1, 2, 3])

In [110]:
torch.from_numpy(array)

tensor([1, 2, 3])

In [111]:
x = torch.tensor([1,2,3])
x.numpy()

array([1, 2, 3])