## BASIC NN

In [2]:
import torch
import torch.nn as nn

In [15]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)

        out = self.linear2(out)
        out = self.sigmoid(out)



        return out

In [16]:
# Create dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Forward Pass
model(features)

tensor([[0.6007],
        [0.6208],
        [0.6060],
        [0.6051],
        [0.6136],
        [0.6094],
        [0.6022],
        [0.6133],
        [0.6055],
        [0.5986]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear1.weight

Parameter containing:
tensor([[-0.3803,  0.0597, -0.0840, -0.1333, -0.2459],
        [-0.3248,  0.2603,  0.1999,  0.0175, -0.2328],
        [ 0.1881, -0.0101, -0.2629,  0.3515,  0.0838]], device='cuda:0',
       requires_grad=True)

In [19]:
model.linear1.bias

Parameter containing:
tensor([-0.3460, -0.3756,  0.0901], requires_grad=True)

In [20]:
from torchinfo import summary

summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## IMPROVED NN

In [22]:
import torch
import torch.nn as nn

In [23]:
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),

            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):
        return self.network(features)    

In [24]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.6455],
        [0.6521],
        [0.6705],
        [0.6593],
        [0.6551],
        [0.6464],
        [0.6264],
        [0.6534],
        [0.6615],
        [0.6289]], grad_fn=<SigmoidBackward0>)

In [25]:
summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00