In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
x, y = make_classification(
    n_samples=10, 
    n_features=2, 
    n_informative=2, 
    n_redundant=0,
    n_classes=2
)

In [3]:
x

array([[ 0.15773311, -2.89856018],
       [ 1.57385688,  1.04382937],
       [ 1.74084542,  0.46848387],
       [ 0.3128644 , -1.18413311],
       [-0.39843734,  1.29725696],
       [-1.61918877, -0.91408554],
       [ 0.11912913,  0.39346555],
       [ 0.18546987,  0.9451393 ],
       [ 0.11100534, -3.05023784],
       [-0.95049048, -0.77682466]])

In [4]:
y

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 0])

In [7]:
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [8]:
x

tensor([[ 0.1577, -2.8986],
        [ 1.5739,  1.0438],
        [ 1.7408,  0.4685],
        [ 0.3129, -1.1841],
        [-0.3984,  1.2973],
        [-1.6192, -0.9141],
        [ 0.1191,  0.3935],
        [ 0.1855,  0.9451],
        [ 0.1110, -3.0502],
        [-0.9505, -0.7768]])

In [9]:
y

tensor([1., 1., 1., 0., 0., 0., 0., 1., 1., 0.])

In [13]:
from torch.utils.data import DataLoader, Dataset

In [23]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]


    def __getitem__(self, index):
        return self.features[index], self.labels[index]            

In [24]:
dataset = CustomDataset(x, y)

In [25]:
len(dataset)

10

In [26]:
dataset[0]

(tensor([ 0.1577, -2.8986]), tensor(1.))

In [27]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [28]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print('-'*40)

tensor([[-0.3984,  1.2973],
        [-0.9505, -0.7768]])
tensor([0., 0.])
----------------------------------------
tensor([[0.1191, 0.3935],
        [0.1855, 0.9451]])
tensor([0., 1.])
----------------------------------------
tensor([[-1.6192, -0.9141],
        [ 0.1577, -2.8986]])
tensor([0., 1.])
----------------------------------------
tensor([[ 1.5739,  1.0438],
        [ 0.3129, -1.1841]])
tensor([1., 0.])
----------------------------------------
tensor([[ 1.7408,  0.4685],
        [ 0.1110, -3.0502]])
tensor([1., 1.])
----------------------------------------
